pizza_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzeria.urls')),
    path('users/', include('users.urls')),
]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'pizzeria'

urlpatterns = [
    path('',views.index, name='index'),
    path('pizzas',views.pizzas, name='pizzas'),
    path('pizza/<int:pizza_id>',views.pizza, name='pizza'),
    path("pizza/<int:pizza_id>/comment", views.comment, name="comment"),
    path("admin/", admin.site.urls),
]

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

pizzeria/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Pizza(models.Model):
    pizza_name = models.CharField(max_length=200)

    def __str__(self):
        return self.pizza_name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping_name = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'toppings'

    def __str__(self):
        return f"{self.topping_name [:50]}" 


class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    comment = models.TextField(max_length=200)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.comment [:50]}" 

users/models.py
from django.db import models

# Create your models here.

pizzeria/forms.py
from django import forms

from .models import Pizza, Topping, Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']
        labels = {'comment': ''}
        widgets = {'comment': forms.Textarea(attrs={'cols':80})}

pizzeria/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from pizzeria.models import Pizza, Topping, Comment
from .forms import CommentForm

# Create your views here.
def index(request):
    return render(request, 'pizzeria/index.html')

def pizzas(request):
    pizzas = Pizza.objects.filter()

    context = {'pizzas':pizzas}

    return render(request, 'pizzeria/pizzas.html', context)

def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)

    toppings = pizza.topping_set.order_by('topping_name')

    comments = pizza.comment_set

    context = {'pizza':pizza,'toppings':toppings, 'comments':comments}

    return render(request, 'pizzeria/pizza.html', context)

@login_required
def comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)

    if request.method != "POST":
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.pizza = pizza
            comment.owner = request.user
            comment.save()
            return redirect("pizzeria:pizza", pizza_id=pizza_id)

    context = {"form": form, "pizza": pizza}

    return render(request, "pizzeria/comment.html", context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):

    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('pizzeria:index')

    context = {'form':form}
    return render(request, 'registration/register.html', context) 

pizzeria/templates/pizzeria/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang='en'>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content='width=device-width, initial-scale=1, shrink-to-fit=no'>
    <title>Josh's Pizzeria</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>

</html>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'pizzeria:index' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pizzeria:pizzas' %}">
                        Pizzas
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text" }">Hello, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>

</html>

pizzeria/templates/pizzeria/comment.html
{% extends "pizzeria/base.html" %}


{% block content %}

<form action="{% url 'users:register' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}

    <button name="submit">Add comment</button>

</form>

{% endblock content %}

pizzeria/templates/pizzeria/index.html
{% extends "pizzeria/base.html" %}

{% block content %}
<p>
    Josh's Pizzeria
</p>
<p>
    Home of your friendly neighborhood pizza guys.

    <body>
        <iframe src="https://giphy.com/embed/4ayiIWaq2VULC" width="600" height="400" frameBorder="0" class="giphy-embed"
            allowFullScreen></iframe>
        <p><a href="https://giphy.com/gifs/pizza-unicorn-i-love-4ayiIWaq2VULC"></a></p>
    </body>
</p>

{% endblock content %}

pizzeria/templates/pizzeria/pizza.html
{% extends "pizzeria/base.html" %}


{% block content %}
<p>
    Toppings:
</p>

<ul>
    {% for t in toppings %}

    <li>
        <p>{{ t.topping_name }}</p>
    </li>
    {% empty %}
    <li>
        There are no toppings for this pizza.
    </li>
    {% endfor %}
</ul>

{% endblock content %}

pizzeria/templates/pizzeria/pizzas.html
{% extends "pizzeria/base.html" %}


{% block content %}
<p>Pizzas</p>

<ul>
    {% for p in pizzas %}

    <li>
        <p> <a href="{% url 'pizzeria:pizza' p.id %}"> {{ p }} </a></p>
    </li>
    {% empty %}
    <li> There are no pizzas available.</li>
    {% endfor %}
</ul>

{% endblock content %}